### ISSUE TITLE
IAM Policy Note

### ISSUE THREAD

**Issue by muddman** [stuart-warren/chef-aws-tag#1]
This is extremely useful, thanks very much for providing it!!

Two quick notes about the last line of the readme.  First, I found that I needed to apply the policy to the "Default IAM instance profile" at the stack level or the "EC2 Instance profile" if the default is overridden in the layer and not to the Opsworks IAM role (applying it here didn't work for me).  Second, I needed DescribeTags in addition to Create and Delete.

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ec2:CreateTags",
        "ec2:DeleteTags",
        "ec2:DescribeTags"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}

Cheers and thanks again!

**Comment by stuart-warren** [comment]
Glad someone else found it useful!
