### ISSUE TITLE
cookbook dependencies

### ISSUE THREAD

**Issue by lynnegithub** [stuart-warren/chef-aws-tag#2]
Do I need to have both [aws](https://github.com/chef-cookbooks/aws) and [ohai](https://github.com/chef-cookbooks/ohai) cookbook to run this recipe?

**Comment by stuart-warren** [comment]
It's been a long time since I've used chef, but the metadata only lists:

```
depends 'aws', '>= 0.2.4'
```

the latest `aws` cookbook seems to depend on `ohai` but it didn't do so before

**Comment by lynnegithub** [comment]
oh, I included both aws and ohai in my custom cookbook repo but I still get an `undefined method `config' for Ohai:Module` error during OpsWork setup. Do you have any idea how can I work around this? Thanks!

**Comment by stuart-warren** [comment]
My guess is that you'll need to ensure you are running a version of ohai that is compatible with the version of aws, but I would half expect that to be automatic.
Sorry I can't be more help, I haven't touched Chef/Opsworks in 2 years and even then I barely understood what I was doing. We found Cloudformation (and Ansible) a better solution for our needs.

**Comment by zanzan42** [comment]
Stuart,

Just an FYI, but since OpsWorks moved to using aws-sdk v2 and the AWS/Aws function re-namespacing, the aws dependent cookbook that you're using fails for OpsWorks users (with an "uninitialized constant Aws" error). There's a long issue thread on it that I've been participating in for months here:

https://github.com/chef-cookbooks/aws/issues/104

Not really your problem, but it does affect the functionality of this cookbook since the aws cookbook is a dependency.

**Comment by stuart-warren** [comment]
@zanzan42 thanks for the update!
If you have a tested fix I'll accept it, otherwise this isn't something I'm using myself anymore...

**Comment by maxmonterumisi** [comment]
@zanzan42 thanks for update, but now aws-sdk it's only for ubuntu! 
If I have a windows stack what is the solution ? 
Use aws-2.5.0 ?

**Comment by zanzan42** [comment]
I don’t have any experience with Windows stacks, but there is an aws-sdk for .NET. I imagine one could create Chef LWRPs and recipes using that version of the aws-sdk if they need to do equivalent things under Windows.

At the moment, chef-aws-tag is working in OpsWorks for me under *nix (Amazon Linux, in this case) by explicitly using the 2.5.0 version of the underlying LWRP cookbook. That uses the deprecated right_aws library for execution, and I’m not sure whether that has any Windows compatibility or not. Haven’t really looked at it.

**Comment by maxmonterumisi** [comment]
I have tried with aws 2.5.0 and work without problem under Windows stack.
Thank for your support.

**Comment by stuart-warren** [comment]
Thanks for the details!
